name: Linux
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, x64, debian10, premake5, garrysmod_common]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Generate Project x64
        run: $PREMAKE5 gmake --gmcommon="${GARRYSMOD_COMMON64}"

      - name: "[x64] Build Release With Symbols"
        run: |
          cd projects/linux/gmake
          make -j2 config=releasewithsymbols_x86_64

      - name: Generate Project x32
        run: $PREMAKE5 gmake --gmcommon="${GARRYSMOD_COMMON}"

      - name: "[x32] Build Release With Symbols"
        run: |
          cd projects/linux/gmake
          make -j2 config=releasewithsymbols_x86

      - name: Upload Builds
        uses: actions/upload-artifact@v2
        with:
          name: ReleaseWithSymbols
          path: 
            projects/linux/gmake/x86_64/ReleaseWithSymbols/gmsv_network_linux64.dll

  
  tests:
    needs: build
    runs-on: [self-hosted, linux, x64, debian10, gmod]

    steps:
      - uses: actions/checkout@v2
        # with:
        #   submodules: 'recursive'

      - name: Setup Enviroment Variables
        run: |
          echo GMOD=$GMOD >> $GITHUB_ENV
      
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: ReleaseWithSymbols
          path: ${{ env.GMOD }}/garrysmod/lua/bin/
      
      - name: Copy test.lua
        run: |
          mkdir -p $GMOD/garrysmod/addons/test/lua/autorun/
          cp .github/workflows/test.lua $GMOD/garrysmod/addons/test/lua/autorun/

      - name: Run Garrysmod x64
        working-directory: ${{ env.GMOD }}
        timeout-minutes: 5
        run: ./start64.sh
      
      - name: Print Log
        working-directory: ${{ env.GMOD }}
        run: cat garrysmod/console.log

      - name: Check If Test Successful
        working-directory: ${{ env.GMOD }}
        run: if [[ $(< garrysmod/data/success.txt) != "$GITHUB_SHA" ]]; then exit 1; fi