name: Linux
on:
  push:
  workflow_dispatch:

jobs:
  linux:
    runs-on: [self-hosted, linux, x64, debian10, gmod-module-ready]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Generate Project x64
        run: premake5 gmake --gmcommon="$HOME/garrysmod_common_x86_64"

      - name: "[x64] Build Release With Symbols"
        run: |
          cd projects/linux/gmake
          make -j2 config=releasewithsymbols_x86_64

      - name: Generate Project x32
        run: premake5 gmake --gmcommon="$HOME/garrysmod_common"

      - name: "[x32] Build Release With Symbols"
        run: |
          cd projects/linux/gmake
          make -j2 config=releasewithsymbols_x86

      - name: Upload Builds
        uses: actions/upload-artifact@v2
        with:
          name: ReleaseWithSymbols
          path: 
            projects/linux/gmake/**/*.dll
            
      - run: |
          echo $CI $GITHUB_WORKFLOW
          echo ======================
          env
