name: Linux
on:
  push:
  workflow_dispatch:

jobs:
  linux:
    runs-on: [self-hosted, linux, x64, debian10, gmod-module-ready]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Generate Project
        run: premake5 gmake --gmcommon="$HOME/garrysmod_common"

      - name: "[x64] Build Release With Symbols"
        run: |
          cd projects/linux/gmake
          make -j2 config=releasewithsymbols_x86_64

      - name: "[x32] Build Release With Symbols"
        run: |
          cd projects/linux/gmake
          make -j2 config=releasewithsymbols_x86

      - name: Upload Builds
        uses: actions/upload-artifact@v2
        with:
          name: ReleaseWithSymbols
          path: 
            projects/linux/gmake/x86/ReleaseWithSymbols/gmsv_network_linux.dll
            projects/linux/gmake/x86_64/ReleaseWithSymbols/gmsv_network_linux64.dll
